Sprint 5 fix review #2
ArthurM2/MovieQuiz-ios pull request #15
Opened 2022-09-08 08:42 UTC by ArthurM2

2022-09-09 05:54 UTC, ABashkirova requested changes
Привет! Осталось немного:
- почините вызов методов не с главного потока :)

2022-09-09 05:54 UTC, ABashkirova commented on MovieQuiz/Resources/QuestionFactoryDelegate.swift
> +    func didFailToLoadImage(with error: Error)
Все эти методы реализует класс ViewController'а, позаботьтесь о том, что код обновляющий UI внутри этих методов выполняется на главном потоке. 
- либо оборачивайте реализацию метода во ViewController'е
- либо оборачивайте вызов функции через делегата

Сейчас большая часть из этих функций работает вызывает обновление UI не из главного потока, приложение пишет об этом логи. 

```
MovieQuiz[25673:1612158] [reports] Main Thread Checker: UI API called on a background thread: -[UIView setHidden:]
PID: 25673, TID: 1612158, Thread name: (none), Queue name: com.apple.NSURLSession-delegate, QoS: 0
```

2022-09-09 05:54 UTC, ABashkirova commented on MovieQuiz/Presentation/ResultAlertPresenter.swift
> +     var allCorrectAnswers: Int = 0
```suggestion
    var numberOfQuizGames: Int = 0
    var recordCorrectAnswers: Int = 0
    var recordDate = Date()
    var averageAccuracy: Double = 0.0
    var allCorrectAnswers: Int = 0
```

Советую пользоваться форматтером: выделите весь код и зажмите control + I

2022-09-09 05:54 UTC, ABashkirova commented on MovieQuiz/Resources/QuestionFactory.swift
> +                self.delegate.didLoadDataFromServer()
Здесь сервер может вернуть ошибку в mostPopularMovies. Или пустой список фильмов. Без них - приложение будет вести себя некорректно. 

Давайте обработаем этот случай

2022-09-12 16:17 UTC, ABashkirova requested changes

2022-09-12 16:17 UTC, ABashkirova commented on MovieQuiz/Resources/QuestionFactory.swift
> +
Вернете ошибку на глобальной очереди... затем пойдете собирать вопрос дальше. Здесь нужен выход из функции

2022-09-13 13:07 UTC, ArthurM2 commented on MovieQuiz/Resources/QuestionFactory.swift
> +                self.delegate.didLoadDataFromServer()
@ABashkirova Не совсем понял про errorMessage. Это отдельный кейс?
Допустим, что у меня пришел пустой массив  items: [], тогда отображается вот такая ошибка
<img width="413" alt="image" src="https://user-images.githubusercontent.com/38484496/189909120-1cd70920-5105-4643-8fb1-b24cc000722f.png">
<img width="151" alt="image" src="https://user-images.githubusercontent.com/38484496/189909217-14f78c93-7be1-4ee8-b9ef-1656f92f9097.png">

2022-09-13 13:09 UTC, ArthurM2 commented on MovieQuiz/Resources/QuestionFactory.swift
> +                self.delegate.didLoadDataFromServer()
А если приходит errorMessage с пустым массивом, это уже отдельный кейс?
Или нужен кейс где  errorMessage и массив items не пустой

2022-09-14 14:18 UTC, ArthurM2 commented
@ABashkirova я правильно понял, что для принятия ревью нужна лишь обработка ошибки в errorMessage: "" и если массив не пустой?
1) кейс когда не пришел массив с фильмами и в errorMessage: "" какая-то ошибка 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/38484496/190177749-45be42e2-b2de-4035-8b75-1361e915bc80.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/38484496/190177939-a9e59daf-6b26-4d7a-94b0-3539da90414e.png">
2) кейс когда массив пустой и errorMessage тоже ничего нет
<img width="381" alt="image" src="https://user-images.githubusercontent.com/38484496/190179376-837f1877-c093-4735-b466-96981a36d503.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/38484496/190179422-55a2c2f5-3897-4aeb-8586-c09c068624a1.png">
3) !маловероятно! но вдруг такое, что errorMessage null
<img width="379" alt="image" src="https://user-images.githubusercontent.com/38484496/190179674-bb5a12e0-c417-4024-8b22-0aec33a3736a.png">
<img width="197" alt="image" src="https://user-images.githubusercontent.com/38484496/190179748-5adf784a-d2da-4a67-90ea-81f5f6b0141c.png">

2022-09-14 14:38 UTC, ABashkirova commented on MovieQuiz/Resources/QuestionFactory.swift
> +                }
Проведем тесты, А - список пуст, B - текст ошибки пустой 
Выражение: !A || B 
1.  true, true = true - покажем квиз
2. false, true = true // 
3. false, false = true  // 
4. true, false = false - покажем ошибку, когда список пуст и есть текст об ошибке 

Вроде бы это самый "реальный вариант", но, возможен вариант, когда список пришел пустым, и текст ошибке тоже. И мы пойдем показывать квиз. 

В целом, этого достаточно для этой задачи. Однако, рекомендую всегда на клиенте обрабатывать даже невозможные кейсы – если что-то может произойти, оно обязательно произойдет 😄 двойная защита (на беке и на фронте) не помешает! 

Однако во всем надо держать баланс с точки зрения времени затраченного на обработку кейсов.

Оставлю здесь вариант, как я бы написала этот кусочек. 


```suggestion
            guard  mostPopularMovies.errorMessage.isEmpty else {
                self.delegate.didReceiveEmptyJson(errorMessage: mostPopularMovies.errorMessage)
                return 
            }
            guard  !mostPopularMovies.items.isEmpty else {
                self.delegate.didReceiveEmptyJson(errorMessage: QuestionFactoryError.emptyMovies)
                return 
            }
            self.movies = mostPopularMovies.items
            self.delegate.didLoadDataFromServer()
```

C помощью guard вы отсекаете плохой сценарий, строя happy path, собственно и перевод у оператора защита/охрана. Поэтому он здесь наиболее удобен

2022-09-15 11:39 UTC, ABashkirova reviewed
Привет! Работа принята, 
но есть одно место где надо поправить)

2022-09-15 11:39 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showErrorEmptyJson(message: errorMessage)
Здесь забыто DispatchQueue.main.async

2022-09-15 11:39 UTC, ABashkirova approved these changes

2022-09-15 18:19 UTC, merged